version: "3.8"

services:
  app:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /media/jh/testing/weights:/app/weights
      - /media/jh/testing/videos:/app/videos
    restart: always
    networks:
      - app_network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=detections
    ports:
      - "27017:27017"
    volumes:
      - /media/jh/testing/mongodb/data/db:/data/db 
    restart: always
    networks:
      - app_network 

networks:
  app_network:
    driver: bridge